### ISSUE TITLE
インジケータにborderを付けたい

### ISSUE THREAD

**Issue by uhooi** [delphinus/skkeleton_indicator.nvim#13]
表題の通りです。
インジケータに `border = 'rounded'` のようなパラメータを渡すことで、枠線を付けられるようにしたいです。

**Comment by delphinus** [comment]
<img width="107" alt="スクリーンショット 0005-06-27 16 22 18" src="https://github.com/delphinus/skkeleton_indicator.nvim/assets/1239245/4e346649-3c70-42c9-926c-25f363a01af3">

雑に `border` 付けただけだと枠線だけ浮いて見えちゃいますね。nerd-fonts か何かで、見た目を調整した方がいいかな……

**Comment by uhooi** [comment]
なるほど、背景色が付いているエリアと実際の背景部分が異なるのですね、、
工夫して小さく枠線を付けられればいいのですが、、

**Comment by delphinus** [comment]
点字を使うパターン

<img width="107" alt="スクリーンショット 0005-06-27 17 51 25" src="https://github.com/delphinus/skkeleton_indicator.nvim/assets/1239245/ccbb7d89-f758-4d5f-8b67-e3ed166b5457">

```lua
border = { "⡠", "⠤", "⢄", "⢸", "⠊", "⠒", "⠑", "⡇" },
```

普通にやるなら、これ以上小さな枠線を付けるのは無理かなー。いい感じに、枠の内側だけ色を塗る方法があればいいんですが……

**Comment by delphinus** [comment]
あ、でも、文字を反転して↓このようにすればそれらしく見えるでしょうか？ どうでしょう？

<img width="107" alt="スクリーンショット 0005-06-27 17 55 49" src="https://github.com/delphinus/skkeleton_indicator.nvim/assets/1239245/f28e95e1-ea81-4fe7-8656-0dae2a775411">

**Comment by uhooi** [comment]
あ、よさそうですー！
背景色を付けなければいい感じに見えますね…！

**Comment by delphinus** [comment]
#16 に `border` オプションのヘルプだけ作りました。実装はまだ何もありません。こんな感じで実装しようと思います。

**Comment by uhooi** [comment]
ドキュメントから作るのちゃんとしててすごいです…
完璧過ぎますありがとうございます！！！
