### ISSUE TITLE
モード切り替えが反映されない

### ISSUE THREAD

**Issue by uga-rosa** [delphinus/skkeleton_indicator.nvim#28]
# 概要

Neovim nightlyで、モードを切り替えたときにindicatorが表示するモードが更新されません。

![skkeleton_indicator](https://github.com/delphinus/skkeleton_indicator.nvim/assets/82267684/ace7e0d4-0140-425c-b2a5-3fdd66d4d96a)

0.9.5では起きないので、最近何かしらの変更が入ったのだと思いますが、原因commitまでは調査しきれていません。

## 環境

- NVIM v0.10.0-dev-98d687a
- deno 1.42.1
- denops.vim c057cdff217e3f7de9f19c8da270b23523bb19a4

OS/Terminalは

- OS: Ubuntu 22.04.4 LTS (WSL2) 
- Terminal: Windows Terminal

と

- OS: macOS Sonoma 14.4.1
- Terminal: wezterm 20240203-110809-5046fc22

の両方で確認

## 最小構成

- init.vim
```vim
set runtimepath+=/path/to/denops.vim
set runtimepath+=/path/to/skkeleton
set runtimepath+=/path/to/skkeleton_indicator.nvim

inoremap <C-j> <Plug>(skkeleton-toggle)

lua require('skkeleton_indicator').setup()
```

## 再現手順

1. Insert-mode に入る。「英字」のindicatorが出る。
2. `<C-j>`でひらがなモードに入る。ここで「ひら」に変わるはずだが、変わらない。ハイライトも消える。

**Comment by delphinus** [comment]
取り急ぎ、このコミットが原因のようです。
https://github.com/neovim/neovim/commit/08fc1ebbaa49e3110b65bddeed28d2e61a96f5d9

**Comment by uga-rosa** [comment]
https://github.com/delphinus/skkeleton_indicator.nvim/blob/855c3b98dec42d375d2f7ce5ddeae94331df429b/lua/skkeleton_indicator/indicator.lua#L114

ここをこう変更したら多分直ります。

```diff
-  api.buf_set_lines(buf, 0, 0, false, { mode.text })
+  api.buf_set_lines(buf, 0, -1, false, { mode.text })
```

1行目に文字列追加しても、カーソルが1行目に移動してないってことなんだと。

**Comment by delphinus** [comment]
なるほど！これは元々のバグですね。そのように修正するのが意図として正しいです。

今までは行を追加すると強制的にカーソルが1行目に移動していたのでテキストが変わっていたけど、この修正で元の文字列の場所にカーソルが保持されるようになったので、テキストが変わらないように見えていたんですね。ハイライトが消えていたのは `nvm_buf_clear_namespace` が効いていたからか。

**Comment by uga-rosa** [comment]
ですね。流石にnvim_buf_set_linesががっつり壊れてたら他の人も気付くだろうと思い、nvim_buf_get_linesでindicator bufferの中身確認して気付きました。
PRにしておいたのでお願いします～
