### ISSUE TITLE
setupを再度実行すると表示が重複する

### ISSUE THREAD

**Issue by kawarimidoll** [delphinus/skkeleton_indicator.nvim#5]
起動後に再度`lua require('skkeleton_indicator').setup()`が呼ばれると、`o`で挿入モードに入ったときindicatorが重複して表示されます。
（現実的には、直接`lua require('skkeleton_indicator').setup()`を呼んだのではなく、`init.vim`をリロードしたときに発生しました）

サンプルGifを添付します。
1. `o`で挿入モードに入る→`英字`が表示される
2. `lua require('skkeleton_indicator').setup()`を実行後、 `o`で挿入モードに入る→`英字`が2つ表示される

![Kapture 2021-12-09 at 10 11 25](https://user-images.githubusercontent.com/8146876/145316565-3e1fe314-0405-45ea-8cfa-ea0863aa8e9a.gif)

最小限の設定は以下のとおり（プラグインマネージャにvim-plug使用）です。
```vim
call plug#begin(stdpath('config') . '/plugged')
Plug 'vim-denops/denops.vim'
Plug 'vim-skk/denops-skkeleton.vim'
Plug 'delphinus/skkeleton_indicator.nvim'
call plug#end()
lua require('skkeleton_indicator').setup()

imap <C-j> <Plug>(skkeleton-toggle)
cmap <C-j> <Plug>(skkeleton-toggle)
```

**Comment by delphinus** [comment]
ありがとうございます。`autocmd` が `setup{}` を呼ぶたびに増殖しておりました。修正済です。

**Comment by kawarimidoll** [comment]
迅速な修正ありがとうございます！
