### ISSUE TITLE
highlight stops working after loading some colorscheme

### ISSUE THREAD

**Issue by Matts966** [delphinus/skkeleton_indicator.nvim#7]
Like https://github.com/cocopon/iceberg.vim/issues/90, some colorscheme uses `hi clear` to clear previous colorscheme.
This removes [skkeleton_indicator.nvim](https://github.com/delphinus/skkeleton_indicator.nvim)'s highlight.

**Comment by Matts966** [comment]
I forgot to say thank you for this artifact.
The statusline is insufficient as I can't check the mode in my sight while writing.

Also, this issue is not confirmed in `37669aa699258b6dcbec85e3ed866ecc5d4c0713` and the commit `eb16c7325f530add0a365def0509880433bf5240` seems to be the cause.

**Comment by delphinus** [comment]
@Matts966 Thank you for reporting. I made a patch to solve this: #8. I will merge after you check it.

**Comment by Matts966** [comment]
@delphinus 
That works perfectly! Thank you 🎉
